//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace common.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLlt08_diagnostico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLlt08_diagnostico()
        {
            this.CLlt16_tratamiento = new HashSet<CLlt16_tratamiento>();
        }
    
        public long idDiagnostico { get; set; }
        public string descDiagnostico { get; set; }
        public long idAtencion { get; set; }
        public Nullable<int> idCie10 { get; set; }
    
        public virtual CLlt03_atencion CLlt03_atencion { get; set; }
        public virtual CLlt04_cie10 CLlt04_cie10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLlt16_tratamiento> CLlt16_tratamiento { get; set; }
    }
}
