//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace common.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLlt11_evolucion
    {
        public long idEvolucion { get; set; }
        public string descEvolucion { get; set; }
        public Nullable<bool> pesimo { get; set; }
        public Nullable<bool> malo { get; set; }
        public Nullable<bool> regular { get; set; }
        public Nullable<bool> bueno { get; set; }
        public Nullable<bool> excelente { get; set; }
        public long idAtencion { get; set; }
    
        public virtual CLlt03_atencion CLlt03_atencion { get; set; }
    }
}
