//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace common.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLlt15_seguroPaciente
    {
        public int idSeguro { get; set; }
        public long idPaciente { get; set; }
        public Nullable<System.DateTime> fecVencimiento { get; set; }
        public bool activo { get; set; }
        public System.DateTime fecRegistro { get; set; }
        public Nullable<System.DateTime> fecModificacion { get; set; }
        public Nullable<System.DateTime> fecEliminacion { get; set; }
        public string idUsuario { get; set; }
        public string idUsuarioModificar { get; set; }
        public string idUsuarioEliminar { get; set; }
    
        public virtual CLlt14_seguro CLlt14_seguro { get; set; }
        public virtual RHUt07_paciente RHUt07_paciente { get; set; }
    }
}
