//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace common.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLlt10_estudioCompl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLlt10_estudioCompl()
        {
            this.CLIt02_archivoEstudioCompl = new HashSet<CLIt02_archivoEstudioCompl>();
        }
    
        public long idEstudioCompl { get; set; }
        public string descEstudioCompl { get; set; }
        public long idAtencion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIt02_archivoEstudioCompl> CLIt02_archivoEstudioCompl { get; set; }
        public virtual CLlt03_atencion CLlt03_atencion { get; set; }
    }
}
