//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace common.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLlt05_cita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLlt05_cita()
        {
            this.CLlt03_atencion = new HashSet<CLlt03_atencion>();
            this.CLlt06_citaDtl = new HashSet<CLlt06_citaDtl>();
            this.TNSt05_estadoDeCuenta = new HashSet<TNSt05_estadoDeCuenta>();
            this.TNSt01_comprobanteEmitido = new HashSet<TNSt01_comprobanteEmitido>();
        }
    
        public long idCita { get; set; }
        public string codCita { get; set; }
        public System.DateTime fecCita { get; set; }
        public System.DateTime fecRegistro { get; set; }
        public Nullable<System.DateTime> fecModificacion { get; set; }
        public string horaInicio { get; set; }
        public string duracionEstimada { get; set; }
        public byte numReprogramacion { get; set; }
        public bool esOnline { get; set; }
        public bool esCerrado { get; set; }
        public Nullable<long> idCitaPadre { get; set; }
        public string obsvCita { get; set; }
        public decimal mtoTotal { get; set; }
        public short idEstadoCita { get; set; }
        public long idPaciente { get; set; }
        public long idEmpleado { get; set; }
        public string idUsuario { get; set; }
        public string idUsuarioModificar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLlt03_atencion> CLlt03_atencion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLlt06_citaDtl> CLlt06_citaDtl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TNSt05_estadoDeCuenta> TNSt05_estadoDeCuenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TNSt01_comprobanteEmitido> TNSt01_comprobanteEmitido { get; set; }
        public virtual CLlt09_estadoCita CLlt09_estadoCita { get; set; }
        public virtual RHUt01_empleado RHUt01_empleado { get; set; }
        public virtual RHUt07_paciente RHUt07_paciente { get; set; }
    }
}
