//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace common.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROt03_productoUnidadDeMedida
    {
        public int idUnidadDeMedida { get; set; }
        public long idProducto { get; set; }
        public decimal precio { get; set; }
        public Nullable<decimal> precioMinimo { get; set; }
        public Nullable<decimal> precioMaximo { get; set; }
        public bool activo { get; set; }
        public System.DateTime fecRegistro { get; set; }
        public Nullable<System.DateTime> fecModificacion { get; set; }
        public Nullable<System.DateTime> fecEliminacion { get; set; }
        public string idUsuario { get; set; }
        public string idUsuarioModificar { get; set; }
        public string idUsuarioEliminar { get; set; }
    
        public virtual PROt02_producto PROt02_producto { get; set; }
        public virtual PROt06_unidadDeMedida PROt06_unidadDeMedida { get; set; }
    }
}
