//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace common.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RHUt02_empleadoEspecialidad
    {
        public long idEmpleado { get; set; }
        public int idEspecialidad { get; set; }
        public System.DateTime fecRegistro { get; set; }
        public Nullable<System.DateTime> fecModificacion { get; set; }
        public Nullable<System.DateTime> fecEliminacion { get; set; }
        public bool activo { get; set; }
        public string idUsuario { get; set; }
        public string idUsuarioModificar { get; set; }
        public string IdUsuarioEliminar { get; set; }
    
        public virtual RHUt01_empleado RHUt01_empleado { get; set; }
        public virtual RHUt04_especialidad RHUt04_especialidad { get; set; }
    }
}
