//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace common.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RHUt10_personaRedSocial
    {
        public int idRedSocial { get; set; }
        public long idPersona { get; set; }
        public string nombrePerfil { get; set; }
        public string obsvPerfil { get; set; }
        public bool activo { get; set; }
        public System.DateTime fecRegistro { get; set; }
        public Nullable<System.DateTime> fecModificacion { get; set; }
        public Nullable<System.DateTime> fecEliminacion { get; set; }
        public string idUsuario { get; set; }
        public string idUsuarioModificar { get; set; }
        public string idUsuarioEliminar { get; set; }
    
        public virtual MSTt03_redSocial MSTt03_redSocial { get; set; }
        public virtual RHUt09_persona RHUt09_persona { get; set; }
    }
}
