//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace common.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TNSt05_estadoDeCuenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TNSt05_estadoDeCuenta()
        {
            this.TNSt03_cuota = new HashSet<TNSt03_cuota>();
        }
    
        public long idEstadoDeCuenta { get; set; }
        public decimal porcentajeDescuento { get; set; }
        public decimal mtoDescuento { get; set; }
        public decimal mtoSubtotal { get; set; }
        public decimal debe { get; set; }
        public decimal haber { get; set; }
        public decimal saldo { get; set; }
        public decimal inicial { get; set; }
        public decimal porcentajeInteres { get; set; }
        public decimal mtoInteres { get; set; }
        public System.DateTime fecRegistro { get; set; }
        public Nullable<System.DateTime> fecModificacion { get; set; }
        public string idUsuario { get; set; }
        public string idUsuarioModificar { get; set; }
        public long idCita { get; set; }
    
        public virtual CLlt05_cita CLlt05_cita { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TNSt03_cuota> TNSt03_cuota { get; set; }
    }
}
