//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace common.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TNSt02_comprobanteEmitidoDtl
    {
        public long idComprobanteEmitidoDtl { get; set; }
        public decimal precio { get; set; }
        public decimal cantidad { get; set; }
        public long idComprobanteEmitido { get; set; }
        public long idCitaDtl { get; set; }
    
        public virtual CLlt06_citaDtl CLlt06_citaDtl { get; set; }
        public virtual TNSt01_comprobanteEmitido TNSt01_comprobanteEmitido { get; set; }
    }
}
